name: Keep Repo Fresh

on:
  schedule:
    - cron: "3 3 3 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: filewrite
        run: date > dummy/dummy.txt
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Keep Repo fresh'
