name: Daily run
on:
  schedule:
    - cron: "7 21 * * *"

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: ./sync.ps1
          shell: pwsh
          env:
            TONIEPWD: ${{ secrets.PASSWORD }}
            TONIEUSR: ${{ secrets.USERNAME }}
