name: Manual
on: [workflow_dispatch]

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script
          env:
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
          run: ./sync.ps1 "$Env:username" "$Env:password"
          shell: pwsh
