name: Manual
on: [workflow_dispatch]

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: ./sync.ps1
          shell: pwsh
          env:
            MyVariable: ${{ secrets.MY_VARIABLE }}
